export { sparql } from './lib/sparql'
export { turtle } from './lib/turtle'
export { nquads } from './lib/nquads'
export { ntriples } from './lib/ntriples'
export type { SparqlTemplateResult, SparqlValue } from './lib/sparql'
export type { TurtleTemplateResult, TurtleValue } from './lib/turtle'
export type { NQuadsTemplateResult, NQuadsValue } from './lib/nquads'
export type { NTriplesTemplateResult, NTriplesValue } from './lib/ntriples'
