export { default as prefixes } from '@zazuko/prefixes'
export { sparql } from './lib/sparql.js'
export { turtle } from './lib/turtle.js'
export { nquads } from './lib/nquads.js'
export { ntriples } from './lib/ntriples.js'
export type { SparqlTemplateResult, SparqlValue, SparqlOptions } from './lib/sparql.js'
export type { TurtleTemplateResult, TurtleValue, TurtleOptions } from './lib/turtle.js'
export type { NQuadsTemplateResult, NQuadsValue, NQuadsOptions } from './lib/nquads.js'
export type { NTriplesTemplateResult, NTriplesValue, NTriplesOptions } from './lib/ntriples.js'
