export { default as prefixes } from '@zazuko/prefixes'
export { sparql } from './lib/sparql.js'
export { turtle } from './lib/turtle.js'
export { nquads } from './lib/nquads.js'
export { ntriples } from './lib/ntriples.js'
export type { SparqlTemplateResult, SparqlValue } from './lib/sparql.js'
export type { TurtleTemplateResult, TurtleValue } from './lib/turtle.js'
export type { NQuadsTemplateResult, NQuadsValue } from './lib/nquads.js'
export type { NTriplesTemplateResult, NTriplesValue } from './lib/ntriples.js'
